### ISSUE TITLE
Potential Type Error

### ISSUE THREAD

**Issue by liux-pro** [cpldcpu/BitNetMCU#9]
Hi
I found a possible error. 
The int8_t type `weightChunk` is being left-shifted by 8 bits with weightChunk <<= 8;. 
int8_t should be int32_t ?

https://github.com/cpldcpu/BitNetMCU/blob/9815b44cd310dbd57413878a29a4b9ac4b0e45de/BitNetMCU_inference.c#L156-L161

**Comment by cpldcpu** [comment]
You are right! Fixed, thank you!
